name: Terraform Plan

on:
  - pull_request

jobs:
  plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install qemu-utils
        run: |
          sudo apt update
          apt install -y qemu-utils 

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubactions-tf-openstack-provider

      - name: Auth GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/455628669441/locations/global/workloadIdentityPools/github-actions/providers/gha-tf-openstack-provider'

      - uses: smallstep/action-install-step-cli@main

      - name: Bootstrap Step CLI
        run: |
          sudo step ca root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt --ca-url https://hl-us-homelab1-step-ca.tailnet-047c.ts.net --fingerprint 111301fb085dfc83f5390c0be68df3d68f5584853df0cb4c442383c33f2bd83a
          sudo chmod 0644 /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
          sudo update-ca-certificates
          curl https://hashi-vault-1.us-homelab1.hl.rmb938.me:8200/v1/sys/health\?standbyok=true | jq .
          echo "STEP_CA=$(sudo cat /usr/local/share/ca-certificates/smallstep-homelab-prod.crt | base64 -w 0)" >> $GITHUB_ENV

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://hashi-vault-1.us-homelab1.hl.rmb938.me:8200
          caCertificate: ${{ env.STEP_CA }}
          role: gha_rmb938_tf_openstack_provider
          method: jwt
          path: jwt-gha
          exportToken: true
          secrets: |
            secret/openstack-keystone/project-users/project_provider_user_provider-tf project_name | OS_PROJECT_NAME ;
            secret/openstack-keystone/project-users/project_provider_user_provider-tf application_credential_id | OS_APPLICATION_CREDENTIAL_ID ;
            secret/openstack-keystone/project-users/project_provider_user_provider-tf application_credential_secret | OS_APPLICATION_CREDENTIAL_SECRET ;

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out tfplan

      # https://github.com/hashicorp/vault-action/issues/427
      - name: Revoke Vault Token
        if: always()
        run: |
          curl -XPOST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" https://hashi-vault-1.us-homelab1.hl.rmb938.me:8200/v1/auth/token/revoke-self 
